In [2]:
import os
os.chdir(r'C:\Users\Perry_Lu\Desktop\ebm\正课\课程\MLDE\IMA\data\brazilian-ecommerce')

# Binary Classification

## Model training

In [3]:
# Random Forest Classification

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

# Importing the dataset
dataset = pd.read_csv('dataset.csv')
dataset = dataset.dropna().reset_index(drop=True)
X = dataset.iloc[:,2:6].values
y = dataset.iloc[:,-1].values
print(set(y))
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)#数据集比例划分

# Feature Scaling
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

from sklearn.model_selection import GridSearchCV

tuned_parameters = [{
                     'max_depth': [3, 5, 7],
                     'min_samples_split': [3, 5, 7],
                     'max_features': ["sqrt", "log2", None]}]

scores = [ 'f1_macro']

for score in scores:
    print("# Tuning hyperparameters for %s" % score)
    print("\n")
    clf = GridSearchCV(RandomForestClassifier(class_weight="balanced"), tuned_parameters, cv=5,
                       scoring= score)
    clf.fit(X_train, y_train)
    print("Best parameters set found on the training set:")
    print(clf.best_params_)
    print("\n")
    

{0, 1}
# Tuning hyperparameters for f1_macro


Best parameters set found on the training set:
{'max_depth': 3, 'max_features': 'sqrt', 'min_samples_split': 7}




## Prediction

In [4]:
#  Fitting Random Forest to the Training set
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0,class_weight = 'balanced',max_depth= 3, max_features= 'sqrt', min_samples_split= 7 )
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,f1_score,accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(f'confusion_matrix is: \n{cm}')
print(f'f1_score is: {f1_score(y_test,y_pred,average="binary")}')

confusion_matrix is: 
[[ 1222  3636]
 [  611 17019]]
f1_score is: 0.8890688259109312


# 3Class Classification

## Model training

In [5]:
# Random Forest Classification

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

# Importing the dataset
dataset = pd.read_csv('dataset.csv')
dataset = dataset.dropna().reset_index(drop=True)
X = dataset.iloc[:,2:6].values
y = dataset.iloc[:,-2].values
print(set(y))
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)#数据集比例划分

# Feature Scaling
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

from sklearn.model_selection import GridSearchCV

tuned_parameters = [{
                     'max_depth': [3, 5, 7],
                     'min_samples_split': [3, 5, 7],
                     'max_features': ["sqrt", "log2", None]}]

scores = ['f1_macro']

for score in scores:
    print("# Tuning hyperparameters for %s" % score)
    print("\n")
    clf = GridSearchCV(RandomForestClassifier(class_weight="balanced"), tuned_parameters, cv=5,
                       scoring= score)
    clf.fit(X_train, y_train)
    print("Best parameters set found on the training set:")
    print(clf.best_params_)
    print("\n")

{0, 1, 2}
# Tuning hyperparameters for f1_macro


Best parameters set found on the training set:
{'max_depth': 7, 'max_features': 'sqrt', 'min_samples_split': 3}




## Prediction

In [6]:
#  Fitting Random Forest to the Training set
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0,class_weight = 'balanced',max_depth= 7, max_features= 'sqrt', min_samples_split= 3 )
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,f1_score,accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(f'confusion_matrix is: \n{cm}')
print(f'f1_score is: {f1_score(y_test,y_pred,average="macro")}')

confusion_matrix is: 
[[1342 1185 2331]
 [ 264 1501 2724]
 [ 594 3780 8767]]
f1_score is: 0.4348687931928312
