In [33]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.tree import DecisionTreeClassifier as DTC


# Importing the dataset
dataset = pd.read_csv('machine_data_for_student_4.csv')
dataset = dataset.dropna().reset_index(drop=True)
X = dataset.iloc[:,1:-1].values
y = dataset.iloc[:,-1].values
print(set(y))

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
# from sklearn.preprocessing import StandardScaler
# sc_X = StandardScaler()
# X_train = sc_X.fit_transform(X_train)
# X_test = sc_X.transform(X_test)

from sklearn.model_selection import GridSearchCV

tuned_parameters = [{'criterion': ['entropy','gini'],
                     'max_depth': [3, 5,7],
                     'min_samples_split': [3, 5, 7],
                     'max_features': ["sqrt", "log2", None]}]

scores = ['accuracy']

for score in scores:
    print("# Tuning hyperparameters for %s" % score)
    print("\n")
    clf = GridSearchCV(DTC(class_weight="balanced"), tuned_parameters, cv=5,
                       scoring= score)
    clf.fit(X_train, y_train)
    print("Best parameters set found on the training set:")
    print(clf.best_params_)
    print("\n")

{0, 1, 2}
# Tuning hyperparameters for accuracy


Best parameters set found on the training set:
{'criterion': 'entropy', 'max_depth': 7, 'max_features': None, 'min_samples_split': 3}




In [36]:
X_test

array([[1.620e+02, 2.095e+02, 2.500e+01, ..., 1.610e+01, 1.730e+01,
        1.000e+01],
       [4.100e+01, 1.155e+02, 1.000e-01, ..., 6.210e+01, 2.200e+01,
        2.980e+01],
       [1.790e+02, 2.432e+02, 1.640e+01, ..., 2.100e+01, 6.000e+01,
        8.800e+00],
       ...,
       [2.990e+02, 2.932e+02, 7.420e+01, ..., 2.400e+00, 1.106e+02,
        4.170e+01],
       [5.400e+01, 2.221e+02, 5.230e+01, ..., 6.220e+01, 4.960e+01,
        4.640e+01],
       [2.020e+02, 2.554e+02, 1.499e+02, ..., 5.240e+01, 7.740e+01,
        2.640e+01]])

In [40]:
clf.best_score_

0.8607449856733526

In [19]:
X[0]

array([1.87000e+02, 2.38700e+02, 1.42600e+02, 4.40000e+01, 4.40000e+00,
       5.14000e+01, 7.71800e+02, 4.46900e+02, 1.89300e+02, 6.17000e+01,
       7.20000e+00, 1.49865e+04, 1.98000e+01, 1.10000e+01, 4.80000e+00,
       4.67000e+01, 2.16000e+01, 6.80000e+00])

In [24]:
X.shape

(2182, 18)

In [26]:
X[0:2].shape

(2, 18)

In [28]:
clf.predict(X[0:2])

array([1, 2], dtype=int64)

In [29]:
from joblib import dump, load
dump(clf, 'machines_model.joblib') 

['machines_model.joblib']

In [32]:
clf = load('machines_model.joblib')

In [10]:
y.shape

(2182,)